version: '3.4'

volumes:
  mosquitto-data:
  mosquitto-logs:

services:
  minecraft-server:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      SERVER_NAME: "YOUR SERVER"
      ALLOW_CHEATS: "true"
      # ALLOW_LIST_USERS: "user1,user2,user3"
      LEVEL_TYPE: DEFAULT
    ports:
      - 19132:19132/udp
    volumes:
      - /path/to/your/data:/data
    labels:
      minecraft_bedrock_server: "true"
    stdin_open: true
    tty: true
    sysctls:
      net.ipv4.ip_local_port_range: 39132 39133

  minecraft-rest:
    image: macchie/minecraft-bedrock-server-bridge
    container_name: minecraft-rest
    restart: unless-stopped
    depends_on:
      - minecraft-server
    environment:
      - ENABLE_API=true
    ports:
      - 17394:17394
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

  mosquitto_test:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_test
    restart: unless-stopped
    depends_on:
      - mosquitto
    command: "mosquitto_sub -h mosquitto -I message_logger -F '\e[92m%t \e[96m%p\e[0m' -q 0 -t '#'"

  webhook:
    image: ghcr.io/edward3h/mc-webhook:0.4
    container_name: webhook
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webhook-config.yml:/config.yml

  ansible-rulebook:
    build:
      dockerfile: eda-dockerfile
    container_name: ansible-rulebook
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./eda:/eda
    command: >
      ansible-rulebook
      --rulebook /eda/minecraft-rulebook.yml
      --inventory /eda/inventory.yml
      --source-dir /eda/
      --verbose
