- name: Minecraft events
  hosts: localhost
  sources:
    - mqtt:
        host: mosquitto
        topic: messages

  rules:
    - name: Player has connected to server
      condition: event.type == "PLAYER_CONNECTED"
      action:
        run_playbook:
          name: /eda/minecraft_cmd.yml