- name: Minecraft events
  hosts: localhost
  sources:
    - mqtt:
        host: mosquitto
        topic: messages

  rules:
    - name: Respond to player spawn events
      condition: event.container.name == "minecraft-server" and event.mc_event_type == "Spawned"
      action:
        run_playbook:
          name: /eda/minecraft-playbook.yml
