version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      SERVER_NAME: "McNs"
      ALLOW_CHEATS: "true"
      ALLOW_LIST_USERS: "DadRobots,RebelPilot21587,ElsieGoober"
      LEVEL_TYPE: DEFAULT
    ports:
      - 19132:19132/udp
    volumes:
      - /path/to/your/data:/data
    labels:
      minecraft_bedrock_server: "true"
    stdin_open: true
    tty: true
    sysctls:
      net.ipv4.ip_local_port_range: 39132 39133

  bds_bridge:
    image: macchie/minecraft-bedrock-server-bridge
    environment:
      #- TELEGRAM_BOT_TOKEN=12345
      #- TELEGRAM_BOT_ADMINS=username1,username2
      - ENABLE_API=true
    ports:
      - 17394:17394
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  webhook:
    image: ghcr.io/edward3h/mc-webhook:0.4
    restart: "unless-stopped"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/config.yml